name: Check Dependency

on:
  pull_request:
  push:

jobs:
  build:
    name: Check .so file
    runs-on: ubuntu-latest
    steps:
      - name: Show list files
        run: ls

      - name: Check dependency
        run: |
          ldd ./libgl4es_114.so
          ldd ./libltw.so
          ldd ./libOSMesa.so