name: Check Dependency

on:
  pull_request:
  push:

jobs:
  build:
    name: Check .so file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Check dependency
        run: |
          objdump -x ./libgl4es_114.so
          objdump -x ./libltw.so
          objdump -x ./libOSMesa.so